In [18]:
%matplotlib inline
import numpy as np
import pandas as pd

np.random.seed(29)

## Example Problems

[Carnival Dice Rolls]

You are at a carnival and come across a person in a booth offering you a game of "chance" (as people in booths at carnivals tend to do).

You pay 5 dollars and roll 3 dice. If the sum of the dice rolls is greater than 12, you get 15 dollars. If it's less than or equal to 12, you get nothing.

Assuming the dice are fair, should you play this game? 

- How would this change if the winning condition was a sum greater than or equal to 12?


In [19]:
##Keep track by using a 2 dimensional matrix

n_trial = nrows = 10_000
n_die = ncols = 3

rolls=np.random.choice([1,2,3,4,5,6],n_trial * n_die).reshape(nrows, ncols)
rolls

array([[6, 4, 5],
       [6, 3, 1],
       [1, 2, 2],
       ...,
       [6, 2, 1],
       [3, 4, 3],
       [4, 2, 4]])

In [20]:
#adding up the rows of 3 columns (3 die) to help us see the probability of getting a dice roll greater than 12
sums_by_trial = rolls.sum(axis=1)
sums_by_trial

array([15, 10,  5, ...,  9, 10, 10])

In [9]:
#convert columns into boolean values based on x>12
wins = sums_by_trial > 12
wins

array([False, False,  True, ..., False, False, False])

In [11]:
#we then change these boolean to an int again, to gain 1 and 0 for the rows that are >12
win_rate=wins.astype(int).mean()
win_rate

0.2655

In [14]:
#with that win rate, let's look at our profit
expected_winnings = win_rate * 15 
cost = 5
expected_profit = expected_winnings - cost
expected_profit

-1.0174999999999996

#### This is showing us that we should probably expected to lose a litte over $1 each time we play.

In [15]:
#let's answer the next part of the question:

How would this change if the winning condition was a sum greater than or equal to 12?

In [21]:
wins = sums_by_trial >= 12
win_rate = wins.astype(int).mean()
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit

0.5860000000000003

#### If we changed just the sum being >= 12, then we could expect to earn about 58cents each play

___________________________________________________________________

### No Rest or Relaxation

There's a 30% chance my son takes a nap on any given weekend day. What is the chance that he takes a nap at least one day this weekend? What is the probability that he doesn't nap at all?

In [23]:
p_nap = 0.3 #30% probability
ndays = ncols = 2 #two columns for two weekend days (sat/Sun)
n_simulated_weekends = nrows = 10**5 #100000 trials run

To find if a nap is taken or not, we will use np.random.random and say anything less than or equal to our probability (30%) IS a nap taken.

In [25]:
data = np.random.random((nrows, ncols))
data

array([[0.46762045, 0.70078355],
       [0.18897809, 0.54312897],
       [0.253291  , 0.43836437],
       ...,
       [0.15008559, 0.37577491],
       [0.34690321, 0.58934311],
       [0.97135998, 0.57219933]])

In [26]:
#let's turn them to boolean so we can turn it into 1 and 0
naps = data < p_nap
naps

array([[False, False],
       [ True, False],
       [ True, False],
       ...,
       [ True, False],
       [False, False],
       [False, False]])

In [27]:
naps.sum(axis=1)

array([0, 1, 1, ..., 1, 0, 0])